name: vegetables_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  carousel_slider: ^5.1.1
  google_fonts: ^4.0.0
  flutter_rating_bar: ^4.0.1
  razorpay_flutter: ^1.3.5
  flutter_riverpod: ^2.1.3
  dio: ^5.4.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

